[battery]
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
style = 'bold #ff5555'
threshold = 40

[bun]
format = 'via [ğŸ” $version](bold green) '

[character]
disabled = false
error_symbol = "[â¯](bold #ff5555)"
success_symbol = "[â¯](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
truncation_length = 5 
style = "bold #bd93f9"

[docker_context]
disabled = true

[git_branch]
style = "bold #ff79c6"

[git_metrics]
added_style = "bold #50fa7b"
deleted_style = "bold #ff5555"
disabled = false

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[memory_usage]
disabled = false
format = 'via $symbol[${ram} (${ram_pct})]($style) '	
style = 'bold dimmed #ff5555'
symbol = 'ğŸ”¥ '
threshold = 85

[package]
disabled = true

[sudo]
disabled = false
style = 'bold green'
symbol = 'ğŸ§™ '

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
